Weight windows
FRENSIE/FRENSIE pull request #200
Opened 2020-08-23 23:00 UTC by psbritt

Weight windows have been added to FRENSIE, along with an addition of particle importances for an upcoming update and a small update to the observer discretization infrastructure to allow for location of weight window discretization indices using arbitrary phase space dimension discretization indices. Methods have been tested.

No infrastructure for inputting the weight windows has been created yet - the archiving infrastructure has been created in this case due to other tests requiring it to pass.

2020-08-31 02:41 UTC, aprobinson commented on packages/monte_carlo/event/population_control/src/MonteCarlo_PopulationControl.cpp
> +  return std::shared_ptr<PopulationControl>( new DefaultPopulationController );
This is fine but you may consider std::make_shared in the future

2020-08-31 02:48 UTC, aprobinson commented on packages/monte_carlo/event/population_control/src/MonteCarlo_WeightWindow.cpp
> +    }else if(weight < window->lower_weight)
In FRENSIE we typically put the else if/else statements on a new line

2020-08-31 02:54 UTC, aprobinson commented on packages/monte_carlo/event/population_control/src/MonteCarlo_WeightWindow.hpp
> +  virtual std::shared_ptr<WeightWindow> getWeightWindow( ParticleState& particle ) const = 0;
Returning a std::shared_ptr from a function like this has a non-trivial amount of overhead. The smart pointer object will increase the reference count by one and then decrease it by one after this object is destroyed. If the intent is to look up the weight window associated with the particle's current location, energy, direction, etc., and then apply the weight window, it is fine to operate on raw pointers. As this is also part of the protected interface these raw pointers will be isolated from the rest of the code where they could cause issues with data persistence.

2020-08-31 02:59 UTC, aprobinson commented on packages/monte_carlo/event/population_control/src/MonteCarlo_WeightWindowMesh.hpp
> +  void setWeightWindowMap( std::unordered_map<Utility::Mesh::ElementHandle, std::vector<std::shared_ptr<WeightWindow>>>& weight_window_map );
Can there be different types of weight window objects stored at each phase space point? If not you can improve performance by using std::vector<MyWeightWindow>. Unfortunately the vector of shared_pointers causes memory fragmentation since each shared_ptr requires its own call to new whereas the std::vector simply does one call to new [N]. If you're trying to keep things as general as possible it's not a problem though.

2020-08-31 03:00 UTC, aprobinson commented on packages/monte_carlo/event/population_control/src/MonteCarlo_WeightWindowMesh.hpp
>  // Save the collision forcer data to an archive
I think this comment was copied from the collision forcer

2020-08-31 15:16 UTC, psbritt commented
I didn't implement any specific tests for archiving for the population
controllers, but I put archive macros in the population controller files so
that the particle simulation manager tests would pass. I don't know how to
test the archiving abilities of population controllers specifically.

On Sun, Aug 30, 2020 at 10:06 PM Alex Robinson <notifications@github.com>
wrote:

> *@aprobinson* commented on this pull request.
>
> I only had a few comments/suggestions for improvements Philip. Also, did
> you implement archiving with the new population control classes? If so did
> you create unit tests for those?
> ------------------------------
>
> In
> packages/monte_carlo/event/population_control/src/MonteCarlo_WeightWindowMesh.hpp
> <https://github.com/FRENSIE/FRENSIE/pull/200#discussion_r479864229>:
>
> >
> +};
> +
>  // Save the collision forcer data to an archive
>
> I think this comment was copied from the collision forcer
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/FRENSIE/FRENSIE/pull/200#pullrequestreview-478280078>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AD7KYAPVNAGPRO6GRYB3X6DSDMHTVANCNFSM4QI45MFA>
> .
>

2020-08-31 15:35 UTC, psbritt commented on packages/monte_carlo/event/population_control/src/MonteCarlo_WeightWindow.hpp
> +  virtual std::shared_ptr<WeightWindow> getWeightWindow( ParticleState& particle ) const = 0;
I'm not sure I understand. Before, I thought smart pointers on their own (neglecting the underlying object) were essentially equivalent to native types in their overhead in terms of creation and deletion. What do you mean by increase the reference count by one and then decrease it by one after the object is destroyed? If that just means the pointer itself points to something and then doesn't, how does that create a lot of overhead?

2020-09-01 02:00 UTC, aprobinson commented on packages/monte_carlo/event/population_control/src/MonteCarlo_WeightWindow.hpp
> +  virtual std::shared_ptr<WeightWindow> getWeightWindow( ParticleState& particle ) const = 0;
std::shared_ptr implements a design pattern called reference counting smart pointer. Each time the pointer is copied, it increments an internal counter to keep track of how many smart pointer objects are currently pointing to the memory. When a smart pointer object is deleted, the reference count goes down by one. When the reference count goes to zero, that smart pointer object handles freeing the memory that was originally allocated. Reference counting smart pointers do have additional overhead compared to raw pointer types. In this context, where you know that the returned pointer will never be NULL, you can eliminate the overhead and simply return a raw pointer. Better yet, you can return a const reference (return the dereferenced pointer), which would make it even clearer that getWeightWindow can never return a NULL pointer.

2020-09-01 02:04 UTC, aprobinson commented
So you probably want an archive test for the WeightWindow class and the WeightWindowMesh class. You would archive a base class pointer, then create an object from the archive, and finally run some tests to ensure that the state of the object was indeed preserved. There are some examples of this in the estimator unit tests.

2020-09-01 02:33 UTC, psbritt commented
Funnily enough, I implemented the const reference suggestion you made already in the last update PR!

> On Aug 31, 2020, at 9:00 PM, Alex Robinson <notifications@github.com> wrote:
> 
> ﻿
> @aprobinson commented on this pull request.
> 
> In packages/monte_carlo/event/population_control/src/MonteCarlo_WeightWindow.hpp:
> 
> > +public:
> +
> +  //! Constructor
> +  WeightWindowBase()
> +  { /* ... */ }
> +
> +  //! Destructor
> +  ~WeightWindowBase()
> +  { /* ... */ }
> +
> +  void checkParticleWithPopulationController( ParticleState& particle, 
> +                                              ParticleBank& bank) const;
> +
> +protected:
> +
> +  virtual std::shared_ptr<WeightWindow> getWeightWindow( ParticleState& particle ) const = 0;
> std::shared_ptr implements a design pattern called reference counting smart pointer. Each time the pointer is copied, it increments an internal counter to keep track of how many smart pointer objects are currently pointing to the memory. When a smart pointer object is deleted, the reference count goes down by one. When the reference count goes to zero, that smart pointer object handles freeing the memory that was originally allocated. Reference counting smart pointers do have additional overhead compared to raw pointer types. In this context, where you know that the returned pointer will never be NULL, you can eliminate the overhead and simply return a raw pointer. Better yet, you can return a const reference (return the dereferenced pointer), which would make it even clearer that getWeightWindow can never return a NULL pointer.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-09-02 16:04 UTC, psbritt commented
Would I need to archive both a pointer to the weight window base and the population controller? What about the weight window struct?

2020-09-02 16:19 UTC, bam241 commented on packages/monte_carlo/event/population_control/src/MonteCarlo_WeightWindowMesh.hpp
> +//! \author Philip Britt
I would keep Alex name there, (and add yours after his)

2020-09-02 16:20 UTC, bam241 commented on packages/monte_carlo/event/population_control/src/MonteCarlo_WeightWindowMesh.hpp
> +  typedef unsigned discretization_bin_index;
is this actually used ?

2020-09-02 16:21 UTC, bam241 commented on packages/monte_carlo/event/population_control/test/tstWeightWindowMesh.cpp
> +  FRENSIE_CHECK_CLOSE(14.2/3, particle_bank.top().getWeight(),1e-14);
why choose `1e-14`

2020-09-02 16:21 UTC, bam241 commented on packages/monte_carlo/event/population_control/test/tstWeightWindowMesh.cpp
> +  FRENSIE_CHECK_CLOSE(14.2/3, particle_bank.top().getWeight(),1e-14);
and `1e-13` below ?

2020-09-02 16:32 UTC, psbritt commented on packages/monte_carlo/event/population_control/src/MonteCarlo_WeightWindowMesh.hpp
> +//! \author Philip Britt
I'm not sure whether or not that's appropriate since I did a full rewrite of the class.

2020-09-02 16:44 UTC, psbritt commented on packages/monte_carlo/event/population_control/src/MonteCarlo_WeightWindowMesh.hpp
> +//! \author Philip Britt
The diff seems to make it clear this is the case, since the external behavior of the entire class changed, and I left Alex's authorship on the actual implementation of the weight windows in the particle simulation manager, though...

2020-09-02 16:52 UTC, psbritt commented on packages/monte_carlo/event/population_control/test/tstWeightWindowMesh.cpp
> +  FRENSIE_CHECK_CLOSE(14.2/3, particle_bank.top().getWeight(),1e-14);
It was a typo, I meant to set it at 1e-15 (close to machine precision).

2020-09-02 17:05 UTC, psbritt commented on packages/monte_carlo/event/population_control/src/MonteCarlo_WeightWindowMesh.hpp
> +  typedef unsigned discretization_bin_index;
It was at one point but I stopped using it and forgot to delete this typedef.

2020-09-02 19:22 UTC, psbritt commented
> So you probably want an archive test for the WeightWindow class and the WeightWindowMesh class. You would archive a base class pointer, then create an object from the archive, and finally run some tests to ensure that the state of the object was indeed preserved. There are some examples of this in the estimator unit tests.

I'm looking through `tstSurfaceFluxEstimator.cpp` and I have to confess, I don't understand it. What's the point of having a pointer to the base class and the derived class if you're just going to set the pointer to the base class as equal to the pointer to the derived class? At that point, aren't you just making modifications and archiving the same object? I see that later you check if both pointers are still equal after the archiving, but I'm not sure what that accomplishes. Is there something under the hood of the archiving stuff that could potentially change the memory address?

2020-09-03 03:29 UTC, aprobinson commented on packages/monte_carlo/event/population_control/src/MonteCarlo_WeightWindowMesh.hpp
> +//! \author Philip Britt
I appreciate the concern @bam241 and generally I agree with you. After reviewing this class so much has changed that I'm ok with Philip taking sole ownership. My initial "implementation" was really just a placeholder as well.

2020-09-03 03:48 UTC, aprobinson requested changes

2020-09-03 03:48 UTC, aprobinson commented on packages/monte_carlo/event/population_control/src/MonteCarlo_WeightWindow.cpp
> +    const WeightWindow window = this->getWeightWindow(particle);
const WeightWindow& window = ...
Make sure it's a reference here.

2020-09-03 03:48 UTC, aprobinson commented on packages/monte_carlo/event/population_control/src/MonteCarlo_WeightWindowMesh.hpp
>    void save( Archive& ar, const unsigned version ) const;
If you want you can remove save/load and just use serialize. If you keep save/load you need to add BOOST_SERIALIZATION_SPLIT_MEMBER(); in the private block. If you look at this definition in the boost serialization library it does some template tricks to reroute the call to serialize to either save or load depending on whether the archive is for loading or saving.

2020-09-03 03:48 UTC, aprobinson commented on packages/monte_carlo/event/population_control/test/tstWeightWindowMesh.cpp
> +FRENSIE_UNIT_TEST_TEMPLATE_EXPAND( WeightWindowMesh,
This serialization test looks good. Nicely done!

2020-09-03 03:48 UTC, aprobinson commented on packages/monte_carlo/event/population_control/src/MonteCarlo_WeightWindowMesh.hpp
> +  ar & BOOST_SERIALIZATION_BASE_OBJECT_NVP( WeightWindowBase );
You generally want to call this first. While in this case I don't see any problems you want to think of these methods almost like constructors where the base class's constructor is always called first. This way you know that all of the base class's data has been initialized before you get to the body of the method (where the base class's data may be used).

2020-09-03 03:48 UTC, aprobinson commented on packages/monte_carlo/event/population_control/src/MonteCarlo_WeightWindowMesh.hpp
> +  ar & BOOST_SERIALIZATION_BASE_OBJECT_NVP( WeightWindowBase );
See my previous comment.

2020-09-03 14:54 UTC, psbritt commented on packages/monte_carlo/event/population_control/src/MonteCarlo_WeightWindow.cpp
> +    const WeightWindow window = this->getWeightWindow(particle);
What's the difference between the way it was implemented and adding the &? I understand one is a reference and one is an object, but I figured in this syntax they'd be functionally equivalent, especially since it compiled.

2020-09-04 20:08 UTC, psbritt commented
I don't think separating this PR into 2 separate PRs is appropriate, since the reshuffling of files was actually the deletion of some empty classes that were originally intended to be the population control classes before this PR but accidentally got included into another PR well before this, and the renaming of the weight_windows directory to population control are still well-related to the content of this PR and honestly aren't really worth the time investment to untangle this PR into 2 separate ones. I intend to leave it as it is. Going forward, I can make the PRs more concise in their purpose, though.

2020-09-14 17:49 UTC, gonuke requested changes
This looks pretty good to me.  A few little comments.

2020-09-14 17:49 UTC, gonuke commented on packages/monte_carlo/manager/src/MonteCarlo_ParticleSimulationManagerFactory.hpp
> +  ar & BOOST_SERIALIZATION_NVP( d_population_controller );
This is here twice.

2020-09-14 17:49 UTC, gonuke commented on packages/monte_carlo/event/population_control/test/tstWeightWindowMesh.cpp
> +  FRENSIE_CHECK_CLOSE(14.2/3, photon.getWeight(), 1e-14);
calculate survival weight only once (and avoid magic number)

2020-09-14 17:49 UTC, gonuke commented on packages/monte_carlo/event/population_control/test/tstWeightWindowMesh.cpp
> +      for(int i = 0; i < 2; ++i)
use  variable that indicates which dimension you are looping over

2020-09-14 17:49 UTC, gonuke commented on packages/monte_carlo/event/population_control/test/tstWeightWindowMesh.cpp
> +    MonteCarlo::PhotonState photon(0);
Might want to actually test the data in the WW mesh object rather than just invoke the WW mesh.

For reference, check the serialization tests for the standard mesh class and other discretizations.

2020-09-15 18:15 UTC, psbritt commented on packages/monte_carlo/core/src/MonteCarlo_ParticleState.cpp
> +void ParticleState::updateImportance( const double new_importance )
By monitoring the collision number of the particle, which is inherited by all secondary particles produced from reactions or split particles. It'll be included in the next PR.

2020-09-15 18:16 UTC, psbritt commented on packages/monte_carlo/core/src/MonteCarlo_ParticleState.cpp
> +    d_importance_pair( std::make_pair(1.0, 1.0))
The collision number of the particle enables it to be positive it's been set appropriately.

2020-09-15 21:17 UTC, gonuke commented on packages/monte_carlo/core/src/MonteCarlo_ParticleState.cpp
> +void ParticleState::updateImportance( const double new_importance )
To be clear... this means it's enforced by convention.  There is no defensive programming that checks whether `updateImportance()` is called to soon.

2020-09-15 21:23 UTC, gonuke requested changes
Just some comments about the modified tests - nearly there..

2020-09-15 21:23 UTC, gonuke commented on packages/monte_carlo/event/population_control/test/tstWeightWindowMesh.cpp
> +  FRENSIE_CHECK_CLOSE(photon.getWeight(), split_weight,  1e-14);
why different tolerances for these tests

2020-09-15 21:23 UTC, gonuke commented on packages/monte_carlo/event/population_control/test/tstWeightWindowMesh.cpp
> +    FRENSIE_CHECK_EQUAL(underlying_mesh->getNumberOfElements(), 2);
Should you test this first to make sure the above loop is valid?

2020-09-15 21:23 UTC, gonuke commented on packages/monte_carlo/event/population_control/test/tstWeightWindowMesh.cpp
> +    base_archive_test->getDiscretization<MonteCarlo::ObserverPhaseSpaceDimension::OBSERVER_ENERGY_DIMENSION>(energy_discretization_bounds);
also check the size of `energy_discretization_bounds` and before you effectively loop over this dimension, above?

2020-09-15 22:26 UTC, psbritt commented on packages/monte_carlo/core/src/MonteCarlo_ParticleState.cpp
> +void ParticleState::updateImportance( const double new_importance )
I keep accidentally opening a review on my own PR instead of just commenting...

It's hard for me to say based off of the wikipedia definition of "defensive programming" that I just read. The reasoning is that I don't think it's possible for this to be incorrect.

On emergence (collision_number=0), the first one is called to initialize the first member of the pair. On first collision and re-emission (collision_number=1), the second member is set and the first importance comparison will take place. After that (collision_number > 1), the third method (updateImportance) is called, and the second member is switched to the first member and second member is set to the new importance. I can't think of anything else that can possibly modify the collision number.

That being said, since this is in the ParticleState class, I could add some exceptions if the collision number is incorrect for that method.

2020-09-15 22:26 UTC, psbritt commented on packages/monte_carlo/event/population_control/test/tstWeightWindowMesh.cpp
> +  FRENSIE_CHECK_CLOSE(photon.getWeight(), split_weight,  1e-14);
This was a mistake. They should all be 1e-15.

2020-09-15 22:28 UTC, psbritt commented on packages/monte_carlo/event/population_control/test/tstWeightWindowMesh.cpp
> +    FRENSIE_CHECK_EQUAL(underlying_mesh->getNumberOfElements(), 2);
Yes, since otherwise it could produce seg faults and never get to that part of the test.

2020-09-15 23:37 UTC, psbritt commented
Changes made based on Paul's most recent requests

2020-09-16 00:52 UTC, aprobinson approved these changes

2020-09-16 15:08 UTC, gonuke approved these changes
LGTM

2020-09-16 15:14 UTC, merged

2020-09-16 15:16 UTC, gonuke commented
BTW - @psbritt - generally you should not merge your on PR's

2020-09-16 15:25 UTC, psbritt commented
Sorry, wasn't thinking while I was working on something else. I can revert and let @bam241 approve

2020-09-16 16:08 UTC, bam241 commented
don't worry about it.

all good for me 👍