Importances
FRENSIE/FRENSIE pull request #205
Opened 2020-09-16 17:00 UTC by psbritt

Importances added alongside weight windows.

2020-09-16 18:14 UTC, bam241 commented on packages/monte_carlo/event/population_control/src/MonteCarlo_Importance.cpp
> +      double importance_fraction = particle.getImportancePair().second/particle.getImportancePair().first;
this is the only common part in your if statement between `> 1` and `== 1`

I believe a:
``` 
if >1
else if ==1
else
```
would be easier to read

2020-09-16 18:18 UTC, bam241 commented on packages/monte_carlo/event/population_control/src/MonteCarlo_Importance.cpp
> +      }
could you had comments to explain the different cases ?

2020-09-16 18:26 UTC, bam241 commented on packages/monte_carlo/event/population_control/src/MonteCarlo_Importance.cpp
> +        }
```suggestion
       unsigned u_imp_frac = ceil(importance_fraction);
        if( Utility::RandomNumberGenerator::getRandomNumber<double>() < 1-std::fmod(importance_fraction, 1))
        {
           u_imp_frac  = floor(importance_fraction);
        }
        this->splitParticle(particle, bank, static_cast<unsigned>(u_imp_frac), 1/importance_fraction);
        }
```

2020-09-16 18:27 UTC, bam241 commented on packages/monte_carlo/event/population_control/src/MonteCarlo_Importance.cpp
> +      }else if(particle.getCollisionNumber() == 1)
```suggestion
      }else
```
as `particle.getCollisionNumber() >= 1` is already tested

2020-09-16 20:04 UTC, psbritt commented on packages/monte_carlo/event/population_control/src/MonteCarlo_Importance.cpp
> +        }
Wouldn't this add unnecessary overhead? I'd be calculating `ceil(importance_fraction)` every time a particle needs to split.

2020-09-16 21:24 UTC, bam241 commented on packages/monte_carlo/event/population_control/src/MonteCarlo_Importance.cpp
> +        }
what about:
unsigned u_imp_frac = 0;

and else {
u_imp_frac = ceil(importance_fraction);
}
?

2020-09-16 21:25 UTC, bam241 commented on packages/monte_carlo/event/population_control/src/MonteCarlo_Importance.cpp
> +        }
(I updated the code to do so...)

2020-09-16 21:59 UTC, psbritt commented on packages/monte_carlo/event/population_control/src/MonteCarlo_Importance.cpp
> +        }
I don't think this would actually compile - I missed the fact that `floor` and `ceil` only return doubles. Which part specifically is offending in terms of style/performance? the static_cast?

2020-09-17 11:25 UTC, gonuke requested changes
This looks generally OK  - a few cleanup ideas.

I'd like to discuss the tests at a S/W meeting

2020-09-17 11:25 UTC, gonuke commented on packages/monte_carlo/event/population_control/src/MonteCarlo_ImportanceMesh.cpp
> +  return d_importance_map.at(d_mesh->whichElementIsPointIn(particle.getPosition()))[discretization_index[0]];
(This Q was probably relevant in the WW class as well...)
I think `discretization_index` can have length > 1, in general.  Does this assume length == 1 or does this assume that only the first element is relevant?

2020-09-17 11:25 UTC, gonuke commented on packages/monte_carlo/event/population_control/src/MonteCarlo_ImportanceMesh.cpp
> +  }
```suggestion
  return (d_mesh->isPointInMesh(particle.getPosition()) && this->isPointInObserverPhaseSpace(observer_particle))
```

2020-09-17 11:25 UTC, gonuke commented on packages/monte_carlo/event/population_control/test/tstImportanceMesh.cpp
> +    MonteCarlo::PhotonState photon(0);
I keep trying to wrap my head around the best way to do this with a loop.  Cut & paste code is a recipe for problems

2020-09-17 11:25 UTC, gonuke commented on packages/monte_carlo/event/population_control/test/tstImportanceMesh.cpp
> +      std::vector<double> x_planes = {0.0, 1.0};
Why can't you use the `importance_mesh` that you established at test initialization?

2020-09-17 11:25 UTC, gonuke commented on packages/monte_carlo/event/population_control/test/tstImportanceMesh.cpp
> +    photon.setWeight(14.2);
Use a variable for this quantity since it's reused elsewhere
`initialWeight = 14.2`

2020-09-17 11:25 UTC, gonuke commented on packages/monte_carlo/event/population_control/test/tstImportanceMesh.cpp
> +    double updated_weight = 14.2*(2.0/3.5);
```suggestion
    double expected_updated_weight = 14.2*(2.0/3.5);
```

2020-09-17 11:25 UTC, gonuke commented on packages/monte_carlo/event/population_control/test/tstImportanceMesh.cpp
> +  std::vector<double> x_planes = {0, 1, 2};
I think it might be helpful to define some of these quantities at global scope and reuse them throughout?

2020-09-17 14:27 UTC, psbritt commented on packages/monte_carlo/event/population_control/src/MonteCarlo_Importance.cpp
> +    if(particle.getCollisionNumber() >= 1)
I agree, but the reason I designed it like that was with the idea that the particle will much more often have a collision number >=1, and so putting collisions == 0 at the end instead of at the front would give a slight performance boost since this method will be called so often.

2020-09-17 14:29 UTC, psbritt commented on packages/monte_carlo/event/population_control/src/MonteCarlo_ImportanceMesh.cpp
> +  return d_importance_map.at(d_mesh->whichElementIsPointIn(particle.getPosition()))[discretization_index[0]];
This assumes length == 1. Since population controllers are currently only applied immediately after a collision, I don't see a case where there could be more than 1 discretization indices.

2020-09-17 14:37 UTC, psbritt commented on packages/monte_carlo/event/population_control/test/tstImportanceMesh.cpp
> +      std::vector<double> x_planes = {0.0, 1.0};
I did it like this so that I know exactly what objects are in what scope and exactly what objects I'm looking at, and letting objects go out of scope in this test makes sure that I'm not making a mistake with the archiving. It's more a device to avoid confusion, since I think I could technically use the mesh that's formed in the test initialization, but the mesh established at test initialization exists over the entire scope.

2020-09-17 17:04 UTC, psbritt commented on packages/monte_carlo/event/population_control/test/tstImportanceMesh.cpp
> +  std::vector<double> x_planes = {0, 1, 2};
If we keep the archiving test as it is then yes, I think it would make sense. Otherwise, if we use the global mesh for the archiving stuff, I'm not sure it makes a difference.

2020-09-17 17:22 UTC, psbritt commented on packages/monte_carlo/event/population_control/test/tstImportanceMesh.cpp
> +    MonteCarlo::PhotonState photon(0);
Instead of doing this with a loop, would it be better to just simplify the individual scopes such that they only contain statements relevant to them?

2020-09-17 18:50 UTC, psbritt commented on packages/monte_carlo/event/population_control/test/tstImportanceMesh.cpp
> +    MonteCarlo::PhotonState photon(0);
Just to reiterate what was said in the meeting so I don't forget...

1. Put the initialization of the importances into a separate test.
2. Design a global method to initialize the photon and bank... Have to think about that a bit.
3. Form a loop for the other test macros.

I think that's it? did I get everything correct?

2020-09-18 01:21 UTC, bam241 commented on packages/monte_carlo/event/population_control/test/tstImportanceMesh.cpp
> +    }
how about ?

```suggestion
    FRENSIE_CHECK(particle_bank.size(), 0);
   
    if( particle_bank.size() == 1)
    {
      FRENSIE_CHECK_CLOSE(photon.getWeight(), expected_updated_weight, 1e-15);
      FRENSIE_CHECK_CLOSE(particle_bank.top().getWeight(), expected_updated_weight, 1e-15);
    }
```

2020-09-18 16:18 UTC, psbritt commented on packages/monte_carlo/event/population_control/test/tstImportanceMesh.cpp
> +    }
I could see doing something like this if I was looking to make a pattern between i and the number of particles that the first particle is split into, but in this context with just 2 iterations, I think it might obfuscate the goal a bit...

2020-09-18 17:33 UTC, psbritt commented on packages/monte_carlo/event/population_control/test/tstImportanceMesh.cpp
> +      std::vector<double> x_planes = {0.0, 1.0};
If possible, I'd like to leave it like this so that the global object data and the archived data tests don't get mixed up. I think it adds another layer of surety that the test is correct - otherwise, I think there's a chance to make a small mistake and end up having a test that's passing which should actually be failing by using the wrong variable in the wrong place.

2020-09-22 03:03 UTC, gonuke commented on packages/monte_carlo/event/population_control/src/MonteCarlo_Importance.cpp
> +        }
I prefer the version of this that just sets a number (double or unsigned) in the conditional rather than setting a function pointer.

2020-09-22 16:22 UTC, psbritt commented on packages/monte_carlo/event/population_control/src/MonteCarlo_Importance.cpp
> +        }
It was originally supposed to be much simpler, but I may have gotten carried away with trying to fix an issue with this. Overloaded functions are not straightforward to assign to a function type, and `ceil` and `floor` are overloaded functions. I can change it to a straightforward number.

2020-09-22 20:09 UTC, gonuke approved these changes

2020-09-22 20:11 UTC, gonuke commented
Thanks @psbritt - this LGTM

2020-09-22 20:11 UTC, merged