Direction discretization feature addition
FRENSIE/FRENSIE pull request #212
Opened 2020-09-29 21:19 UTC by psbritt

Added data member that stores parameters for all spherical triangles to allow for isotropic sampling from triangles and fixes a bug found in the findTriangleBin method.

2020-09-29 21:37 UTC, psbritt commented
I don't know how to convert this to a draft, but I forgot to add archiving stuff to this class while I was inside of it since I didn't know enough to do it the first time. I'll add it tomorrow.

2020-09-30 00:19 UTC, psbritt commented
Archiving has been added and tested.

2020-10-05 18:07 UTC, gonuke requested changes
Consider using semantically meaningful loop variables throughout instead of i, j , k

2020-12-09 23:20 UTC, bam241 reviewed
- For simplicity, I would avoid using `std::array` and use the c-array instead (`int[]`) as you don't use any of the capability the `std::array` bring
(If I understood correctly the main improvement is when you copy them...)
- simplify your looping variable... it would help readability....
- I'd also try to shorten the variables names to improve readability

2020-12-09 23:20 UTC, bam241 commented on packages/utility/direction_discretization/test/tstPQLAQuadrature.cpp
> +      int i = octant;
I'd use I directly.... maybe add a comment saying you are looping over the octant before the `for` loop...

2020-12-09 23:20 UTC, bam241 commented on packages/utility/direction_discretization/src/Utility_PQLAQuadrature.cpp
> +  for(int dimension = 0; dimension < 3; ++dimension)
maybe use `d` instead of `dimension`
 it would help visually

2020-12-09 23:20 UTC, bam241 commented on packages/utility/direction_discretization/src/Utility_PQLAQuadrature.cpp
> +  for(int octant = 1; octant < 8; ++octant)
`i` instead of `octant` ?

2020-12-09 23:20 UTC, bam241 commented on packages/utility/direction_discretization/src/Utility_PQLAQuadrature.cpp
> +             ((v*s + u*t)*sin(std::get<2>(triangle.triangle_parameter_vector[0])));
it is ok to use `s,t,u,v,q`
but put the full formula in comment ?

2020-12-09 23:20 UTC, bam241 commented on packages/utility/direction_discretization/src/Utility_PQLAQuadrature.cpp
> +             ((v*s + u*t)*sin(std::get<2>(triangle.triangle_parameter_vector[0])));
or at least their meaning

2020-12-09 23:20 UTC, bam241 commented on packages/utility/direction_discretization/src/Utility_PQLAQuadrature.cpp
> +}
this time you used `I` for the dimension ?!

2020-12-09 23:20 UTC, bam241 commented on packages/utility/direction_discretization/test/tstPQLAQuadrature.cpp
> +  std::array<size_t, 2> desired_triangles_to_sample_from = {5, 64};
```suggestion
  double desired_triangles_to_sample_from[2] = {5, 64};
```

2020-12-09 23:20 UTC, bam241 commented on packages/utility/direction_discretization/test/tstPQLAQuadrature.cpp
> +      if(i >= 1)
```suggestion
      }
      else if(i >= 1)
```

2020-12-09 23:20 UTC, bam241 commented on packages/utility/direction_discretization/test/tstPQLAQuadrature.cpp
> +      if(i >= 2)
```suggestion
      }
      else if(i >= 2)
```

2020-12-10 19:00 UTC, bam241 commented on packages/utility/direction_discretization/src/Utility_PQLAQuadrature.cpp
> +  size_t number_of_triangles_in_row = 2*d_quadrature_order-1;
```suggestion
  size_t number_of_triangles_in_row = 2*quadrature_order-1;
```

2020-12-14 13:39 UTC, gonuke commented on packages/utility/direction_discretization/src/Utility_PQLAQuadrature.cpp
> +  size_t number_of_rows = quadrature_order;
I agree that using the member variable is cleanest, once it is set

2020-12-14 16:58 UTC, gonuke requested changes
There are a few items to discuss here...

2020-12-14 16:58 UTC, gonuke commented on packages/utility/direction_discretization/src/Utility_PQLAQuadrature.cpp
> +        std::get<0>(local_triangle.triangle_parameter_vector[vert])[0] *= x_multiplier;
I think we need to discuss when/why the use of `get<>` vs just the `[]` accessors?

2020-12-14 16:58 UTC, gonuke commented on packages/utility/direction_discretization/src/Utility_PQLAQuadrature.cpp
> +        std::get<0>(local_triangle.triangle_parameter_vector[vert])[0] *= x_multiplier;
Also - can you just get a reference once and then manipulate that reference?

2020-12-14 16:58 UTC, gonuke commented on packages/utility/direction_discretization/src/Utility_PQLAQuadrature.cpp
>  // Take lower bounding plane indices of direction vector to form triangle index
May be another good place for a detailed comment on the algorithm

2020-12-14 16:58 UTC, gonuke commented on packages/utility/direction_discretization/src/Utility_PQLAQuadrature.cpp
> +void PQLAQuadrature::getSphericalTriangle(const size_t triangle_index,
Also - if this method is private, why not just access to the triangle directly?

2020-12-14 17:04 UTC, bam241 commented on packages/utility/direction_discretization/src/Utility_PQLAQuadrature.cpp
> -  : d_quadrature_order(quadrature_order)
During software, @psbritt explained that he wanted the `testPrecondition` to pass before initialization.

2020-12-14 17:24 UTC, gonuke commented on packages/utility/direction_discretization/src/Utility_PQLAQuadrature.cpp
> +        std::get<0>(local_triangle.triangle_parameter_vector[vert])[0] *= x_multiplier;
`std::array<double, 3>& vertex_coord = get<0>(....)`

2020-12-16 18:18 UTC, bam241 approved these changes
2 minor comments, 
but LGTM!

2020-12-16 18:18 UTC, bam241 commented on packages/utility/direction_discretization/test/tstPQLAQuadrature.cpp
> +  }
Don't understand why this is required, as both object you are binding are vectors.
you could loop over the first one and call the corresponding element in the other vector.

2020-12-16 18:18 UTC, bam241 commented on packages/utility/direction_discretization/src/Utility_PQLAQuadrature.cpp
> +      }
should not it be `dim` in place of `i` ?

2021-04-26 22:28 UTC, psbritt commented
I think all requested changes have been completed for this PR. Can @gonuke confirm and merge if it is?

2021-04-28 02:59 UTC, gonuke commented on packages/utility/direction_discretization/src/Utility_PQLAQuadrature.cpp
> +    for(int tri = 0; tri < triangle_stride; ++tri)
I guess it's prevalent....

2021-04-28 03:07 UTC, gonuke commented
I keep checking back on this PR, but I see a lot of comments unaddressed.

2021-04-28 14:25 UTC, psbritt commented
I was thinking of the ones marked as "outdated" as being addressed and the others I thought we talked about in person. I'll comment on them to make sure they're clear, though.

2021-04-28 15:23 UTC, psbritt commented
I think all of the comments have been addressed or alternate solutions have been proposed.

2021-04-30 10:35 UTC, gonuke commented
I think you misunderstood my comment about parentheses...

I was thinking `for(...` would become `for (...`

You've added extra spaces all over the place, many of which are not really appropriate

2021-04-30 10:52 UTC, gonuke requested changes
I see now that the previous comments were addressed.... GitHub didn't seem to present them to me in an obvious way.

My remaining comment is on the description of your algorithm and the handedness of the implied coordinate system

2021-04-30 10:52 UTC, gonuke commented on packages/utility/direction_discretization/src/Utility_PQLAQuadrature.cpp
> +   * 1 ) Designate coordinate system: To the right is x, to the left is y, and up is z
That's a left handed coordinate system? Maybe this is why I'm confused about how your algorithm matches the diagrams.  You usually draw x to the left and y to the right, and indicate starting on the bottom right.

2021-04-30 10:52 UTC, gonuke commented on packages/utility/direction_discretization/src/Utility_PQLAQuadrature.cpp
>  PQLAQuadrature::PQLAQuadrature(unsigned quadrature_order)
GitHub didn't show the comment added below very clearly...

2021-04-30 10:56 UTC, gonuke commented on packages/utility/direction_discretization/src/Utility_PQLAQuadrature.cpp
> +  for(unsigned i = 0; i<i_y; ++i)
Update this per the discussion in the paper - there is a closed form solution to this.

2021-05-05 02:42 UTC, gonuke approved these changes
Thanks @psbritt

2021-05-05 02:42 UTC, merged