Ndatareaderrefactor
FRENSIE/FRENSIE pull request #221
Opened 2021-05-13 22:46 UTC by lewisgross1296

The long awaited pull request for the Neutron Data Reader refactor is finally here! All tests are passing except test 504 (see Issue #219 ). If merged, Pull Request #196 should be closed, as this one was opened to fix two issues at once. The first issue was resolved in Pull Request #202. This pull request solves the remaining issue and addresses the error found in the data reader. The refactor sorts the given jxs arrays instead of using subtraction of neighbors method, which was found to be incorrect when the block's locators are not increasing monotonically, i.e. data blocks are not ordered in the same ordering as jxs index. Because of this previous logic, some of the FRENSIE tests also propagated this mistake and had to be updated, which can be seen in all the tests that are included in this PR.

2021-05-28 11:40 UTC, gonuke requested changes
There are a few items we can discuss if you like.

2021-05-28 11:40 UTC, gonuke commented on packages/data/ace/test/tstXSSNeutronDataExtractorU238.cpp
> +  FRENSIE_CHECK_EQUAL( dlw_block.back(), 1.910696 ); // TODO Value in line 3047069 first column should be 18, but map thinks 1.91069
I'm not sure what this comment means? Is this the correct value?

2021-05-28 11:40 UTC, gonuke commented on packages/utility/core/test/tstQuantityTraits.cpp
> +  int type_digits = DBL_DIG; // number of correct digits in a (long) double
I'm not a fan of this solutions - we should discuss....

2021-05-28 11:40 UTC, gonuke commented on packages/PyFrensie/test/tstData.ACE.XSSNeutronDataExtractor.py.in
> +        self.assertEqual(len(sig_block), 191)
We should document these changes carefully, somewhere.

2021-05-28 11:40 UTC, gonuke commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.hpp
> +  enum nxsId {    xss_length, // 0, last value position in xss arrary
I know you asked about this and we discussed how to make these accessible to tests.  Perhaps the best solution is to put them in a header and include them in each place where you need them. (possibly at different scopes?)

2021-05-28 11:40 UTC, gonuke commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.hpp
> +  enum nxsId {    xss_length, // 0, last value position in xss arrary
Or just declare these at a different scope outside of the class.

2021-06-07 23:55 UTC, lewisgross1296 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.cpp
> +  std::map<int,std::pair<int,int> >::const_iterator it = block_to_start_length_pair.find(nu);
Where would be the appropriate place for the typedef? Inside some header file or maybe the actual Data_XSSNeutronExtractor.cpp file?

2021-06-08 00:04 UTC, lewisgross1296 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.cpp
> +    }
just committed this change

2021-06-08 00:14 UTC, lewisgross1296 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.cpp
> +  }
I think this is the correct behavior/stopping condition, but I will look more into this in the debugger. The last block is the `end` block, which is the locator of the last word in the ACE file. This is really a pseudo-block and does not have a length if I am correctly interpreting it. Thus we will only want to go to the second to last block, since `int next start = (soi+1)->first` will hit end in order to compute the length of the last block of data (aka the last real block in the enum).

2021-06-08 02:16 UTC, lewisgross1296 commented on packages/utility/core/test/tstQuantityTraits.cpp
> +  int type_digits = DBL_DIG; // number of correct digits in a (long) double
@bam241 helped me with this one, we should include him in this discussion.

2021-06-08 02:32 UTC, lewisgross1296 commented on packages/data/ace/test/tstXSSNeutronDataExtractorU238.cpp
> +  FRENSIE_CHECK_EQUAL( dlw_block.back(), 1.910696 ); // TODO Value in line 3047069 first column should be 18, but map thinks 1.91069
Yep, I meant to delete this comment. This was there while I was finding the correct numbers to use in the tests.

2021-06-08 02:43 UTC, lewisgross1296 commented on packages/PyFrensie/test/tstData.ACE.XSSNeutronDataExtractor.py.in
> +        self.assertEqual(len(sig_block), 191)
Yeah I am not really sure of the proper way to document this. This number change is based of the same change made in tstXSSNeutronExtractorU238.cpp (you can see this and more changes to tests in the files changed).  There is a comment in `packages/data/ace/test/tstXSSNeutronDataExtractorU238.cpp` see line 260. May not be the most complete explanation though. This test in PyFrensie seems to be a duplicate of the one at the path I just mentioned. I am not really sure if the PyFrensie test is actually testing anything new.

2021-06-08 02:52 UTC, lewisgross1296 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.cpp
> +  // need a const iterator since this function is declared const
changed the three functions to this format

2021-06-08 14:04 UTC, bam241 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.hpp
> +  enum nxsId {    xss_length, // 0, last value position in xss arrary
I might be wrong but the test should include this, as it is testing it.... so it should be able to use it...

2021-06-08 17:49 UTC, lewisgross1296 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.cpp
> +    //THROW_EXCEPTION(std::runtime_error, "Entered a forbidden else statement: expected and block to be found in jxs block map ")
Removed

2021-06-08 17:49 UTC, lewisgross1296 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.cpp
> +    THROW_EXCEPTION(std::runtime_error, "Entered a forbidden else statement: expected land block to be found in jxs block map ")
I did not, deleted runtime error and left logic error.

2021-06-08 18:21 UTC, lewisgross1296 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.cpp
> +    // this block has a length defined by the MCNP manual
I know you mentioned this comment for the other non-subtraction blocks. This way is an artifact of the way Alex coded this class. I am not sure doing it in the constructor is too much better than this way. If we were to do that, I  think I would need to manually search for all the blocks without subtractions and modify `map.find(key)->second.second` in the constructor. If there is another reason to move it, I am flexible. But it sounds like I'd just have to remove all this code from each extract function and then move it to the constructor. This would make the extract functions all like each other, which is nice, but since the map is a private data member and nothing outside this class uses it, I think it would be okay to leave it this way. Let me know if I am missing anything important.

2021-06-08 18:23 UTC, lewisgross1296 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.hpp
> +  enum nxsId {    xss_length, // 0, last value position in xss arrary
I think I know how to do the header way, but am less sure about declaring this in the `data` scope. Which file would need to be modified so that all parts of FRENSIE within the data scope would have access to these enums?

2021-06-08 18:33 UTC, lewisgross1296 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.cpp
> +    // because there should always be an key
I think the typo is having "an" instead of "a". Basically both of these blocks are guaranteed to exist in all ACE files. If the if condition is false for these two methods, then there must have been a problem, since there should always be a block in the map with jxs id (key) `andb` and `landb`. This is why there is the if/else with that throws an exception in the else.

2021-06-08 18:59 UTC, lewisgross1296 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.cpp
> +Utility::ArrayView<const double> XSSNeutronDataExtractor::extractNUBlock() const
I am still not sure I understand the proper way to implement this change. Is there a more efficient way to do this than using and if/elseif/else block for each key? (I.e. something like  `if (block_index==nu) {return extractNUBlock()}`) Can we discuss this more in our next meeting (maybe the SW meeting tomorrow, Wednesday 6/9)?

2021-06-08 22:11 UTC, lewisgross1296 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.cpp
>  bool XSSNeutronDataExtractor::hasFissionData() const
Do you mean having the new function `hasData(block_index)` determine the return for `hasFissionData()`, `hasDelaayedNeutronData()`,  and `hasUnresolvedResonanceData()` depending on if block_index is `nu`,`dnu`, or `lunr ? The snippet only shows `hasFissionData()`, but I am guessing this comment applies to all three. To be honest, I am not sure how heavily these functions are used anyways. Maybe in some ace laws.

2021-06-09 17:36 UTC, lewisgross1296 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.cpp
> +  // need a const iterator since this function is declared const
I can try this. We should make sure that an empty ArrayView like `return Utility::ArrayView<const double>()` is interpreted the same was as something like `d_xss_view(0,0)`. I'm not sure a `FRENSIE_CHECK_EQUAL ` is exactly right, but if i recall correctly, there is a way in FRENSIE to see if two objects are the same? Perhaps some digging into the `Utility_ArrayView_def.hpp`. I guess another way is to rebuild with this change and see if any tests break.

2021-06-10 21:00 UTC, lewisgross1296 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.cpp
> +  // need a const iterator since this function is declared const
We did some digging in `Utility::ArrayView` and `Utility::View`, and it seems like an `d_xss_view(0,0)` is the same as `Utility::ArrayView<T>()`. I updated the constructor so that we add the blocks not in `available_blocks` to have a pair of (0,0). I think now I can go through and eliminate the logic since every block is now in the map. We should talk about this to be sure.

2021-06-10 22:38 UTC, lewisgross1296 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.cpp
>  bool XSSNeutronDataExtractor::hasFissionData() const
I just added a `hasData(block_index)` function and called it from those three I mentioned before with the appropriate index. Successful build and test after these changes.

2021-06-11 20:31 UTC, lewisgross1296 commented
I think I have addressed all the above, ready for review on the newest commits. Rebuilt and retested to success. @gonuke

2021-06-14 18:00 UTC, gonuke requested changes
This is looking pretty good.  One more suggestion regarding inline and then we should maybe discuss how we can maximize the QA on the changes to tests.

2021-06-14 18:34 UTC, lewisgross1296 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.cpp
> +Utility::ArrayView<const double> XSSNeutronDataExtractor::extractNUBlock() const
I will add the inline keyword to the signatures. Is it important whether it goes before or after the `const`? I think I'd like to keep the implementation in the `cpp` file, just a personal preference though since I believe all the functions in this class are defined in the `cpp` file.

2021-06-14 18:43 UTC, lewisgross1296 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.cpp
> +Utility::ArrayView<const double> XSSNeutronDataExtractor::extractNUBlock() const
actually it seems like `inline` comes before everything else in the signature, so I will do it like that

2021-06-14 21:01 UTC, lewisgross1296 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.cpp
> +      if(length!=mcnp_length) {
Yeah this is something that I worked on with @bam. I think this would only become a problem if ACE/NJOY changes these length definitions for the blocks with guaranteed lengths. I would guess the MCNP manual got this from NJOY, but am not certain

2021-06-15 23:04 UTC, lewisgross1296 commented
Handled merge conflicts from rebase. Rebuilt and tested. All tests passed except 504 (see Issue #219). @gonuke  I think this is ready for a merge unless we want to remove the allACEFiles.sh and tstXSSNeutronDataExtractorSort.cpp. In which case, I will also take the build instruction out of the modified cmake file

2021-06-16 16:42 UTC, gonuke requested changes
A couple of questions and a request for clear documentation on why the correct values for the test are changing.

2021-06-16 16:42 UTC, gonuke commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.hpp
> +    if(!hasData(landb)) {
Do you know why this is treated differently from the others?

2021-06-16 16:42 UTC, gonuke commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.hpp
> +  }
It's common to write simple inline functions like this on a single line for compactness, especially since there are so many.  
```suggestion
  inline Utility::ArrayView<const double> extractNUBlock() const  { return extractBlock(nu); };
```

2021-06-16 16:42 UTC, gonuke commented on packages/data/ace/test/tstXSSNeutronDataExtractorU238.cpp
> +  FRENSIE_CHECK_EQUAL( sig_block.size(), 191 );
Are you able to provide a detailed description of why these are the correct numbers?  It would also be great if you could surmise/guess/infer why the original numbers were here and why they passed the test before???

What ever you come up with might be best added to the PR description itself, rather than buried in these comments.

2021-06-16 18:12 UTC, lewisgross1296 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.hpp
> +    if(!hasData(landb)) {
Yeah there was an old if/else when we were checking for existence in the map that threw an error if it was not found since this block and the `and` block are always supposed to be found.

2021-06-16 19:14 UTC, lewisgross1296 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.hpp
> +  }
can do

2021-06-16 19:55 UTC, gonuke commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.hpp
> +    if(!hasData(landb)) {
So what about another method `extractBlockRequired(block_idx)` that includes this check and throws a carefully worded exception.   Then your inlined methods can pick and choose which of these to use.

2021-06-16 19:56 UTC, gonuke commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.hpp
> +  inline bool hasFissionData() const
put these on one line too?

2021-06-16 19:56 UTC, lewisgross1296 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.hpp
> +  inline bool hasFissionData() const
ah i missed these, can do

2021-06-16 20:01 UTC, bam241 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.hpp
**nitpick:**  you should "uniformize" the way you use white space

2021-06-16 20:02 UTC, bam241 reviewed
LGTM! 
some small syntax changes ...

2021-06-16 20:09 UTC, lewisgross1296 commented on packages/data/ace/test/tstXSSNeutronDataExtractorU238.cpp
> +  FRENSIE_CHECK_EQUAL( sig_block.size(), 191 );
I can answer here and then add it to the PR description. These are numbers Alex "hunted" for in the ACE file for U238. I am guessing he looked at the sizes of the blocks when they were available in the MCNP manual and if they were not he used his subtraction method for the neighbor block. The reason it passed before was that he was basically looking for these numbers using his assumed understanding of how the blocks worked / something that matched his previous block size implementation, so in the past a size was something like `d_jxs[11]-d_jxs[10]`, so he just took these two numbers and set the size to that.

2021-06-16 20:19 UTC, gonuke commented on packages/data/ace/test/tstXSSNeutronDataExtractorU238.cpp
> +  FRENSIE_CHECK_EQUAL( sig_block.size(), 191 );
There are few enough specific changes, I wonder if we can describe the old approach, and hence the old value and the new approach and the new value in each case.

2021-06-16 20:51 UTC, gonuke commented on packages/data/ace/test/tstXSSNeutronDataExtractorU238.cpp
> +  FRENSIE_CHECK_EQUAL( sig_block.size(), 191 );
I wonder if you can be even more explicit about the changes in these test values.  Something like....

"Using the old method, the length of the block was calculated by subtracting XXX from YYY and therefore resulted in ZZZ/  The correct method does.... resulting in a length of AAAA.  The data that exists at the old location is SSSSS and the data that exists at the correct location is TTTTT"

2021-06-17 17:45 UTC, lewisgross1296 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.hpp
> +    if(!hasData(landb)) {
I can do this to have parallel structure in all the extract blocks in the header (have them all be inlined). I will implement the actual method in the `cpp` file.

2021-06-17 17:58 UTC, lewisgross1296 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.hpp
> +    if(!hasData(landb)) {
Okay so I actually thought about this and since we pass in an int, is there anyway to get the enum name corresponding to that int? Otherwise, I am not sure how to report which block it is without just saying which index it corresponds too. In the for loop in the constructor, the switch statement makes this easy, but I'm not sure how to keep this general in case more blocks eventually use this @gonuke

2021-06-17 18:11 UTC, lewisgross1296 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.hpp
> +    if(!hasData(landb)) {
I guess I could do a switch statement here too, but this would required future developers to add new blocks to the list if they use them. I could write this in the comments for this method

2021-06-17 18:27 UTC, gonuke commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.hpp
> +    if(!hasData(landb)) {
You could pass that value in as another variable to the new method - each of the wrapper functions act as a de facto switch statement

2021-06-17 18:31 UTC, lewisgross1296 commented on packages/data/ace/src/Data_XSSNeutronDataExtractor.hpp
> +    if(!hasData(landb)) {
Gotcha, so I'd pass an int and a string. That is much simpler than what I was trying to do, thanks!

2021-06-17 21:54 UTC, lewisgross1296 commented on packages/data/ace/test/tstXSSNeutronDataExtractorU238.cpp
> +  FRENSIE_CHECK_EQUAL( sig_block.size(), 191 );
Updated PR initial description to reflect this request. Let me know if it is what you're looking for

2021-06-17 22:20 UTC, lewisgross1296 commented on packages/data/ace/test/allACEFiles.sh
> +list_of_paths=$( find /home/software/mcnpdata/xdata/endf71x/ -name "*nc")
I'm not sure I fully understand this comment / how to improve the code here. It also seems like I have some place holder things here to fix as well. Tho if this is non-blocking and everything else is okay, could we maybe merge and then address this after? Would like to start simulations ASAP

2021-06-17 22:48 UTC, gonuke approved these changes
Thanks @lewisgross1296 - this was an important update

2021-06-17 22:48 UTC, merged