Modify CMake to install spectrum plot tools in PyFrensie
FRENSIE/FRENSIE pull request #223
Opened 2021-06-23 22:10 UTC by lewisgross1296

changed install location of `spectrum_plot_tools.py.in` from `{CMAKE_INSTALL_PREFIX}/bin` to PyFrensie

2021-06-24 11:13 UTC, gonuke requested changes
This may work, but is probably not the right way

2021-06-24 11:13 UTC, gonuke commented on tools/post_processing/CMakeLists.txt
> +  DESTINATION ${CMAKE_INSTALL_PREFIX}/lib/python2.7/site-packages/PyFrensie
This is fragile against other python versions- there must be a more standard way to do this by accessing a known path for the current python version

2021-06-24 19:34 UTC, lewisgross1296 commented on tools/post_processing/CMakeLists.txt
> +  DESTINATION ${CMAKE_INSTALL_PREFIX}/lib/python2.7/site-packages/PyFrensie
Is there a more general way to get the installation location to be in PyFrensie without specifying an absolute path that explicitly states the python version? I see your point about someone maybe not installing in exactly `lib/python2.7/site-packages/PyFrensie`. Maybe @psbritt knows a little more about doing this

2021-06-24 19:41 UTC, lewisgross1296 commented on tools/post_processing/CMakeLists.txt
> +  DESTINATION ${CMAKE_INSTALL_PREFIX}/lib/python2.7/site-packages/PyFrensie
Also now that I think about it, this change shouldn't be necessary. I was able to import the method from `spectrum_plot_tools.py.in` in the past with the original version thhis  CMake file and without changing the import in my simulation script (not included in this PR since its in a the `frensie-tests` repo). I am not super sure why it didn't work after the most recent build and install of FRENSIE. Afaik this script is supposed to be accessible after installing FRENSIE without doing this change

2021-06-29 16:57 UTC, gonuke commented
The path for installing PyFrensie is currently defined in `.../packages/PyFrensie/CMakeLists.txt`.  It is hard coded there.  While that's non-ideal, it works for now.  Given the current state, the best thing to do would be to move this definition higher - probably the top level `CMakeLists.txt` file and use it in both places.

2021-06-29 18:31 UTC, lewisgross1296 commented
Build and test of the changes we made succeeded. If you are good with the most recent commit, then this is ready for merge. Otherwise, please let me know about more desired changes. @gonuke

2021-06-29 18:37 UTC, gonuke commented
Thanks @lewisgross1296 - while this still preserves the hard coding of the path, it's at least consistent with the previous definition of the path.

2021-06-29 18:37 UTC, merged